### ISSUE TITLE
CORB-Error

### ISSUE THREAD

**Issue by sbormann** [foxriver76/ioBroker.bring#109] opened 2022-02-04 22:03 UTC
**Describe the bug**
I get thousands of the error messages from below (a few hundreds per second).

**To Reproduce**
Just open vis with the bring widget

**Screenshots & Logfiles**
````
Cross-Origin Read Blocking (CORB) hat die ursprungsübergreifende Antwort https://web.getbring.com/assets/images/items/radiergummi.png mit dem MIME-Typ text/html blockiert. Weitere Informationen finden Sie unter https://www.chromestatus.com/feature/5629709824032768.
Image (async)
buildFragment @ jquery-1.11.2.min.js:3
domManip @ jquery-1.11.2.min.js:3
t.fn.domManip @ can.custom.min.js:28
append @ jquery-1.11.2.min.js:3
checkRecentItems @ index.html?Bring:3750
(anonym) @ index.html?Bring:3839
(anonym) @ conn.js:801
r.onack @ socket.io.js:8
r.onpacket @ socket.io.js:8
(anonym) @ socket.io.js:8
r.emit @ socket.io.js:6
r.ondecoded @ socket.io.js:6
(anonym) @ socket.io.js:8
r.emit @ socket.io.js:6
a.add @ socket.io.js:6
r.ondata @ socket.io.js:6
(anonym) @ socket.io.js:8
r.emit @ socket.io.js:6
r.onPacket @ socket.io.js:6
(anonym) @ socket.io.js:6
r.emit @ socket.io.js:6
r.onPacket @ socket.io.js:7
r.onData @ socket.io.js:7
ws.onmessage @ socket.io.js:8
````
![image](https://user-images.githubusercontent.com/49171332/152609168-415a0789-bb2c-4b12-bc81-0362867ee338.png)

**Versions:**
 - Everything on latest

**Comment by foxriver76** [comment] 2022-02-04 22:16
Which version of chrome

**Comment by sbormann** [comment] 2022-02-04 22:29
Version 97.0.4692.99

**Comment by foxriver76** [comment] 2022-02-05 00:17
I cannot reproduce it. I only get the CORBS warning for item images which cannot be loaded, thus, just the first letter is loaded as fallback. To inform about this, it is totally fine. 

However, there should be once max no. items warning if really no image is available. 

So maybe you can show more from the log file to see if the identical warnings are looped or if its really something different everytime.

**Comment by sbormann** [comment] 2022-02-05 06:51
The loop seems to come from the icon '5' which might come from '5-fach-Steckdose':

![image](https://user-images.githubusercontent.com/49171332/152632002-a20b6880-e0e0-43c1-aaa0-1642914bced1.png)

**Comment by foxriver76** [comment] 2022-02-05 07:33
Ah this might help ;-)

**Comment by foxriver76** [comment] 2022-02-05 07:36
Ha der are not even images in the official app for number 
![8ECEF0B5-431A-48F8-8CE5-78892D32D99D](https://user-images.githubusercontent.com/25484431/152633178-1856dd09-0271-4fd6-afbe-5ca99f69f6b5.jpeg)

**Comment by foxriver76** [comment] 2022-02-05 08:03
Fixed in v.1.7.12

**Closed** 2022-02-05 08:02 UTC

**Comment by sbormann** [comment] 2022-02-05 21:25
Many thanks for the quick fix!
Now there is a broken-image-icon:
![image](https://user-images.githubusercontent.com/49171332/152659515-0ce234d2-2ad2-4588-8358-6c5243f95df4.png)

But i think that is only because numbers are missing at bring`s side. Normaly i do not use numbers, the "5-fach-Steckdose" was a special :) So i think there is no need to fix that.

Best regards!!
